import type { Category, Tag, Business } from './types';
import {
  UtensilsCrossed,
  ShoppingCart,
  HeartPulse,
  Building,
  Car,
  Hotel,
  Briefcase,
  Store,
  Shirt,
  Sparkles,
  Stethoscope,
  Book,
  School,
  Landmark,
  Plane,
} from 'lucide-react';

export const categories: Category[] = [
  { id: 'cat-1', name_en: 'Restaurants', name_ar: 'مطاعم', icon: UtensilsCrossed },
  { id: 'cat-2', name_en: 'Shopping', name_ar: 'تسوق', icon: ShoppingCart },
  { id: 'cat-3', name_en: 'Health', name_ar: 'صحة', icon: HeartPulse },
  { id: 'cat-4', name_en: 'Real Estate', name_ar: 'عقارات', icon: Building },
  { id: 'cat-5', name_en: 'Automotive', name_ar: 'سيارات', icon: Car },
  { id: 'cat-6', name_en: 'Hotels', name_ar: 'فنادق', icon: Hotel },
  { id: 'cat-7', name_en: 'Services', name_ar: 'خدمات', icon: Briefcase },
  { id: 'cat-8', name_en: 'Groceries', name_ar: 'بقالة', icon: Store },
  { id: 'cat-9', name_en: 'Fashion', name_ar: 'أزياء', icon: Shirt },
  { id: 'cat-10', name_en: 'Beauty', name_ar: 'تجميل', icon: Sparkles },
  { id: 'cat-11', name_en: 'Clinics', name_ar: 'عيادات', icon: Stethoscope },
  { id: 'cat-12', name_en: 'Education', name_ar: 'تعليم', icon: Book },
  { id: 'cat-13', name_en: 'Schools', name_ar: 'مدارس', icon: School },
  { id: 'cat-14', name_en: 'Government', name_ar: 'حكومة', icon: Landmark },
  { id: 'cat-15', name_en: 'Travel', name_ar: 'سفر', icon: Plane },
];

export const tags: Tag[] = [
  { id: 'tag-1', name_en: 'Delivery', name_ar: 'توصيل' },
  { id: 'tag-2', name_en: 'Takeaway', name_ar: 'سفري' },
  { id: 'tag-3', name_en: 'Outdoor Seating', name_ar: 'جلسات خارجية' },
  { id: 'tag-4', name_en: 'Family Friendly', name_ar: 'مناسب للعائلات' },
  { id: 'tag-5', name_en: 'Parking', name_ar: 'موقف سيارات' },
  { id: 'tag-6', name_en: 'WiFi', name_ar: 'واي فاي' },
  { id: 'tag-7', name_en: '24/7', name_ar: '٢٤/٧' },
];

export const businesses: Business[] = [
  {
    id: 'biz-1',
    slug: 'chai-halib-pearl',
    name_en: 'Chai Halib',
    name_ar: 'شاي حليب',
    description_en: 'A modern cafe offering traditional Qatari Karak and a variety of teas, coffees, and snacks. Perfect for a quick catch-up or a relaxing break.',
    description_ar: 'مقهى حديث يقدم الكرك القطري التقليدي ومجموعة متنوعة من الشاي والقهوة والوجبات الخفيفة. مثالي للقاء سريع أو استراحة مريحة.',
    category_id: 'cat-1',
    tag_ids: ['tag-1', 'tag-2', 'tag-3', 'tag-6'],
    address_en: 'Porto Arabia, The Pearl, Doha',
    address_ar: 'بورتو أرابيا، اللؤلؤة، الدوحة',
    geo: { lat: 25.375, lng: 51.545 },
    phone: '+974 4444 1234',
    website: 'https://chaihalib.qa',
    opening_hours: {
      'Sat-Thu': '7:00 AM - 11:00 PM',
      'Fri': '7:00 AM - 11:30 AM, 12:30 PM - 11:00 PM',
    },
    price_range: '$$',
    verified_status: true,
    status: 'active',
    rating: 4.5,
    review_count: 345,
    logo_id: 'business-logo-1',
    image_ids: ['business-profile-1'],
  },
  {
    id: 'biz-2',
    slug: 'souq-waqif-art-center',
    name_en: 'Souq Waqif Art Center',
    name_ar: 'مركز سوق واقف للفنون',
    description_en: 'A hub for local and international artists, showcasing contemporary and traditional art. Features galleries, workshops, and art supplies shop.',
    description_ar: 'مركز للفنانين المحليين والدوليين، يعرض الفن المعاصر والتقليدي. يضم صالات عرض وورش عمل ومتجر لمستلزمات الفن.',
    category_id: 'cat-2',
    tag_ids: ['tag-4', 'tag-5'],
    address_en: 'Souq Waqif, Doha',
    address_ar: 'سوق واقف، الدوحة',
    geo: { lat: 25.288, lng: 51.533 },
    phone: '+974 4433 6444',
    website: 'https://swartcenter.qa',
    opening_hours: {
      'Sun-Sat': '9:00 AM - 9:00 PM',
    },
    price_range: '$$$',
    verified_status: true,
    status: 'active',
    rating: 4.8,
    review_count: 512,
    logo_id: 'business-logo-2',
    image_ids: ['business-profile-2'],
  },
  {
    id: 'biz-3',
    slug: 'sidra-medicine',
    name_en: 'Sidra Medicine',
    name_ar: 'مركز السدرة للطب',
    description_en: 'A state-of-the-art hospital specializing in women\'s and children\'s health, offering a wide range of clinical services, research, and education.',
    description_ar: 'مستشفى حديث متخصص في صحة المرأة والطفل، يقدم مجموعة واسعة من الخدمات السريرية والبحوث والتعليم.',
    category_id: 'cat-3',
    tag_ids: ['tag-5', 'tag-7'],
    address_en: 'Al Gharrafa Street, Ar-Rayyan',
    address_ar: 'شارع الغرافة، الريان',
    geo: { lat: 25.326, lng: 51.442 },
    phone: '+974 4003 3333',
    website: 'https://sidra.org',
    opening_hours: {
      'Sun-Sat': '24/7',
    },
    price_range: '$$$$',
    verified_status: true,
    status: 'active',
    rating: 4.9,
    review_count: 890,
    logo_id: 'business-logo-3',
    image_ids: ['business-profile-4'],
  },
  {
    id: 'biz-4',
    slug: 'monoprix-doha-festival-city',
    name_en: 'Monoprix',
    name_ar: 'مونوبري',
    description_en: 'A premium French supermarket offering a wide range of groceries, international products, electronics, and home goods. Features an in-store cafe.',
    description_ar: 'سوبر ماركت فرنسي فاخر يقدم مجموعة واسعة من البقالة والمنتجات العالمية والإلكترونيات والسلع المنزلية. يضم مقهى داخل المتجر.',
    category_id: 'cat-8',
    tag_ids: ['tag-1', 'tag-5'],
    address_en: 'Doha Festival City, Umm Salal Muhammed',
    address_ar: 'دوحة فستيفال سيتي، أم صلال محمد',
    geo: { lat: 25.397, lng: 51.488 },
    phone: '+974 4407 8300',
    website: 'https://monoprix.qa',
    opening_hours: {
      'Sun-Wed': '9:00 AM - 10:00 PM',
      'Thu-Sat': '9:00 AM - 12:00 AM',
    },
    price_range: '$$$',
    verified_status: false,
    status: 'active',
    rating: 4.3,
    review_count: 620,
    logo_id: 'business-logo-1',
    image_ids: ['business-profile-5'],
  },
  {
    id: 'biz-5',
    slug: 'qatar-national-library',
    name_en: 'Qatar National Library',
    name_ar: 'مكتبة قطر الوطنية',
    description_en: 'A national landmark and public library offering access to millions of books, research resources, and a stunning architectural space for reading and learning.',
    description_ar: 'معلم وطني ومكتبة عامة تتيح الوصول إلى ملايين الكتب والمصادر البحثية، ومساحة معمارية مذهلة للقراءة والتعلم.',
    category_id: 'cat-12',
    tag_ids: ['tag-4', 'tag-5', 'tag-6'],
    address_en: 'Education City, Ar-Rayyan',
    address_ar: 'المدينة التعليمية، الريان',
    geo: { lat: 25.318, lng: 51.442 },
    phone: '+974 4454 0100',
    website: 'https://www.qnl.qa',
    opening_hours: {
      'Sat-Thu': '8:00 AM - 8:00 PM',
      'Fri': 'Closed',
    },
    price_range: '$',
    verified_status: true,
    status: 'active',
    rating: 4.9,
    review_count: 1200,
    logo_id: 'business-logo-2',
    image_ids: ['business-profile-3'],
  },
];
